[project]
name = "metadata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "exifread>=3.5.1",
    "tabulate>=0.9.0",
]
